---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pods
spec:
  blockSize: 122
  cidr: 1100:200::/106
  ipipMode: Never
  natOutgoing: true
  nodeSelector: kubernetes.io/hostname != 'ubuntu'
  vxlanMode: Never
  disabled: false
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pods2
spec:
  blockSize: 122
  cidr: 1100:0200:0000:0000:0000:0000:0040:0000/106 
  ipipMode: Never
  natOutgoing: true
  nodeSelector: kubernetes.io/hostname == 'ubuntu'
  vxlanMode: Never
  disabled: false
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: service
spec:
  cidr: 1101:300:1:2::/112
  natOutgoing: true
  disabled: false
  nodeSelector: all()
